# Generated by Django 4.1.5 on 2023-01-08 15:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=70)),
                ('logo', models.ImageField(upload_to='uploads/employers')),
                ('job_title', models.CharField(max_length=70)),
                ('job_description', models.TextField()),
                ('contract_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('working_language', models.CharField(max_length=20)),
                ('job_category', models.CharField(choices=[('IT / SOftware development', 'IT / SOftware development'), ('Design / UX', 'Design / UX'), ('Marketing & Communication', 'Marketing & Communication'), ('Finance', 'Finance'), ('Operations & Support', 'Operations & Support'), ('Other', 'Other')], max_length=40)),
                ('job_link', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('company_size', models.CharField(choices=[('0-10', '0-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000')], max_length=10)),
                ('industry', models.CharField(choices=[('SaaS', 'SaaS'), ('E-commerce', 'E-commerce'), ('Fashion', 'Fashion'), ('Finance', 'Finance'), ('Health', 'Health'), ('Gaming', 'Gaming'), ('Travel', 'Travel'), ('Food', 'Food'), ('Education', 'Education'), ('Transportation', 'Transportation'), ('Music', 'Music'), ('Arts', 'Arts'), ('Others', 'Others')], max_length=25)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
