# Generated by Django 4.1.5 on 2023-01-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='industry',
            field=models.CharField(choices=[('SaaS', 'SaaS'), ('E-commerce', 'E-commerce'), ('Technology', 'Technology'), ('Fashion', 'Fashion'), ('Finance', 'Finance'), ('Health', 'Health'), ('Gaming', 'Gaming'), ('Travel', 'Travel'), ('Food', 'Food'), ('Education', 'Education'), ('Transportation', 'Transportation'), ('Music', 'Music'), ('Arts', 'Arts'), ('Others', 'Others')], max_length=25),
        ),
    ]
