# Generated by Django 4.1.5 on 2023-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_jobpost_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
