# Generated by Django 4.1.5 on 2023-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_jobpost_job_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='logo',
            field=models.ImageField(upload_to='employers'),
        ),
    ]
