# Generated by Django 4.1.5 on 2023-01-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_jobpost_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='candidate_range',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
