# Generated by Django 4.1.5 on 2023-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_jobpost_candidate_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='logo',
            field=models.ImageField(null=True, upload_to='employers'),
        ),
    ]
