# Generated by Django 4.1.5 on 2023-01-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_jobpost_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='candidate_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='employers'),
        ),
    ]
