# Generated by Django 4.1.5 on 2023-01-10 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_alter_jobpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='users')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('personality_note', models.CharField(blank=True, max_length=200, null=True)),
                ('questionnaire', models.JSONField(default=dict)),
                ('applicants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobpost')),
            ],
        ),
    ]
