# Generated by Django 4.1.5 on 2023-01-10 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0013_alter_jobapplication_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='questionnaire',
            new_name='questionnaire_answers',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicants',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='no_of_applicants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='questionnaire',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='users'),
        ),
    ]
