# Generated by Django 4.1.5 on 2023-01-10 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_questionnaire_jobapplication_questionnaire_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applied_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
