# Generated by Django 4.1.5 on 2023-01-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_jobapplication_applied_on_jobpost_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='review',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], max_length=15, null=True),
        ),
    ]
